### ISSUE TITLE
Question about CPUs map

### ISSUE THREAD

**Issue by tylertreat** [jonhoo/drwmutex#8]
I'm wondering why the `cpus` map which maps CPUID to a `RWMutex` index is strictly needed? I.e. wouldn't you get the same effect using `mx[cpu()].RLocker()` where `mx` is sized according to `runtime.NumCPU()`? This would remove the need for platform-specific APICID mappings, but I must be missing something.

**Comment by jonhoo** [comment]
The issue is that `CPUID` returns an APIC ID, which is not just a sequential number starting at 0. Instead, the APIC ID can easily be in the hundreds, even if you have way fewer CPUs than that.

**Comment by tylertreat** [comment]
You could just mod it though, right? `mx[cpu() % NUM_CPU].RLocker()` I haven't tested this to see what the performance is however. For context, I've been looking at how to implement this for macOS. Unfortunately, the options described in https://github.com/jonhoo/drwmutex/issues/5 don't work. All I could manage was a [brute-force hack](https://github.com/tylertreat/drwmutex/commit/04af2cc5fd24a6140a7ad03c60d87b5a0cbaf66d) since Darwin doesn't have `SYS_SCHED_GETAFFINITY`/`SYS_SCHED_SETAFFINITY`.

**Comment by jonhoo** [comment]
It's true that we could mod, though then you (always) end up with contention for certain pairs of unrelated CPUs (mod won't evenly distribute). As for #5, I honestly don't know what the right thing to do is for other platforms (hence the filed and long-open issue). Your workaround will unfortunately likely only work for machines with very few cores, since it's only there that an identity mapping works out. The best pointer I can find for macOS is [this reference](https://stackoverflow.com/questions/33745364/sched-getcpu-equivalent-for-os-x) to `GetCurrentProcessorNumber`. Maybe that'll help?

**Comment by tylertreat** [comment]
Yeah, though unfortunately I don't think the problem is determining the processor a thread is running on. CPUID seems to work fine for that. The problem is building the APIC ID map.

**Comment by jonhoo** [comment]
Ah, no, I was referring to the trick mentioned in #5. Cycle through all the CPUs, use the function for pinning the thread to a single CPU, wait a little while, run CPUID, then move on to the next one. That way you can enumerate the entire mapping.

**Comment by tylertreat** [comment]
> use the function for pinning the thread to a single CPU

Which function is that? Note that Darwin does not support the setaffinity/getaffinity syscalls in Go AFAICT.

Similarly, I'm not sure how to cycle through the CPUs reliably.

**Comment by jonhoo** [comment]
You're right, I misinterpreted. It seems like there aren't even [good workarounds](http://jesperrasmussen.com/2013/03/07/limiting-cpu-cores-on-the-fly-in-os-x/) for doing this on macOS dynamically at runtime :(

**Comment by jonhoo** [comment]
I think the real long-term and interoperable solution here is to enumerate the CPUs using `CPUID` itself. You can invoke it with various arguments to have it give topology information instead of just reporting the current CPU, and that should let you construct the map. It is a *bunch* of work though, which is why I haven't done it :)

**Comment by tylertreat** [comment]
Thanks, I may take a look at doing that at some point.

**Comment by jonhoo** [comment]
Sorry I couldn't be of more help! If you do end up writing it up (the OSDev wiki has [a great step-by-step](http://wiki.osdev.org/Detecting_CPU_Topology_(80x86))), I'd be happy to review and accept a PR.
